In [14]:
import pandas as pd
import pygad
import numpy

# Extração e visualização de dados...
df_raw = pd.read_csv('DSGER.csv', sep=' ', index_col=False)
display(df_raw.head())
# display(df_raw.info())

df = pd.get_dummies(df_raw)
display(df.head())
# display(df.info())

# Algoritmos Genéticos
function_inputs = df.iloc[0].to_list() # Pegando o primeiro registro do dataframe de clientes
print(function_inputs)

desired_output = 0 # Segundo a modelagem, um score maior ou igual a zero significa que o cliente é um bom pagador

def fitness_func(ga_instance, solution, solution_idx):
    output = numpy.sum(solution*function_inputs)
    fitness = 1.0 / numpy.abs(output - desired_output)
    return fitness

fitness_function = fitness_func

num_generations = 600 # Critério de parada, 600 gerações
num_parents_mating = round(len(function_inputs) * 0.1) # número de pais selecionados para reprodução, entre 10% - 20%

sol_per_pop = round(len(function_inputs) * 0.2) # Número de soluções criadas e evoluídas por geração, entre 10% - 20%
num_genes = len(function_inputs) # 62 genes

# Definição do intervalo de geração de genes
init_range_low = -1 # limite do intervalo inferior
init_range_high = 1 # limite do intervalo superior

parent_selection_type = "rws" # Método da roleta
keep_parents = 1 # 10% de elitismo

crossover_type = "single_point" # crossover de 1 corte

# Mutação de aleatória e com taxa de 0.5%
mutation_type = "random"
mutation_percent_genes = 0.5

ga_instance = pygad.GA(num_generations=num_generations,
                       num_parents_mating=num_parents_mating,
                       fitness_func=fitness_function,
                       sol_per_pop=sol_per_pop,
                       num_genes=num_genes,
                       init_range_low=init_range_low,
                       init_range_high=init_range_high,
                       parent_selection_type=parent_selection_type,
                       keep_parents=keep_parents,
                       crossover_type=crossover_type,
                       mutation_type=mutation_type,
                       mutation_percent_genes=mutation_percent_genes)

ga_instance.run()

solution, solution_fitness, solution_idx = ga_instance.best_solution()
print("Parameters of the best solution : {solution}".format(solution=solution))
print("Fitness value of the best solution = {solution_fitness}".format(solution_fitness=solution_fitness))

prediction = numpy.sum(numpy.array(function_inputs)*solution)
print("Predicted output based on the best solution : {prediction}".format(prediction=prediction))

C:\Users\david\AppData\Local\Temp\ipykernel_15156\923824210.py:6: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df_raw = pd.read_csv('DSGER.csv', sep=' ', index_col=False)

,status_conta_corrente,duracao,historico_credito,finalidade,valor_credito,conta_poupanca,emprego_desde,taxa_parcelamento,estado_civil_sexo,outros_devedores,residencia_atual,propriedade,idade,outros_planos_parcelamento,tipo_moradia,numero_creditos,emprego,pessoas_dependentes,telefone,trabalhador_estrangeiro
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,4,A121,67,A143,A152,2,A173,1,A192,A201
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,2,A121,22,A143,A152,1,A173,1,A191,A201
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,3,A121,49,A143,A152,1,A172,2,A191,A201
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,4,A122,45,A143,A153,1,A173,2,A191,A201
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,4,A124,53,A143,A153,2,A173,2,A191,A201

,duracao,valor_credito,taxa_parcelamento,residencia_atual,idade,numero_creditos,pessoas_dependentes,status_conta_corrente_A11,status_conta_corrente_A12,status_conta_corrente_A13,...,tipo_moradia_A152,tipo_moradia_A153,emprego_A171,emprego_A172,emprego_A173,emprego_A174,telefone_A191,telefone_A192,trabalhador_estrangeiro_A201,trabalhador_estrangeiro_A202
0,6,1169,4,4,67,2,1,1,0,0,...,1,0,0,0,1,0,0,1,1,0
1,48,5951,2,2,22,1,1,0,1,0,...,1,0,0,0,1,0,1,0,1,0
2,12,2096,2,3,49,1,2,0,0,0,...,1,0,0,1,0,0,1,0,1,0
3,42,7882,2,4,45,1,2,1,0,0,...,0,1,0,0,1,0,1,0,1,0
4,24,4870,3,4,53,2,2,1,0,0,...,0,1,0,0,1,0,1,0,1,0

C:\Users\david\AppData\Roaming\Python\Python39\site-packages\pygad\pygad.py:641: UserWarning: The percentage of genes to mutate (mutation_percent_genes=0.5) resutled in selecting (0) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).
If you do not want to mutate any gene, please set mutation_type=None.
  if not self.suppress_warnings: warnings.warn("The percentage of genes to mutate (mutation_percent_genes={mutation_percent}) resutled in selecting ({mutation_num}) genes. The number of genes to mutate is set to 1 (mutation_num_genes=1).\nIf you do not want to mutate any gene, please set mutation_type=None.".format(mutation_percent=mutation_percent_genes, mutation_num=mutation_num_genes))

[6, 1169, 4, 4, 67, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0]
Parameters of the best solution : [-1.70483815e-01 -2.38501415e-02  4.35402154e-01 -5.26374471e-01
  3.74445637e-01  6.89187905e-02 -1.05534956e+00  7.93620979e-01
  1.26924649e+00 -1.40585123e+00  2.90927294e-01  1.85028089e+00
  2.71088742e+00  1.13542981e+00  3.47828843e-01 -1.64465734e-01
 -4.14275826e+00  1.49903805e-01 -3.04525777e-01  2.04106853e-01
 -5.98332788e-01 -3.57439269e+00 -2.47379392e+00 -4.01123939e+00
 -2.68302847e+00 -1.48557069e-01  2.04942675e+00 -3.96684221e-01
 -2.29355744e+00 -7.83057668e-01  6.93814881e-01  2.94194995e+00
 -9.33687099e-01 -2.38215877e+00 -1.68237748e+00  2.56891993e-01
 -1.51963786e+00 -3.07722499e-01  8.78049688e-01 -2.16629371e+00
  8.53086044e-01 -1.14487293e+00  1.52910050e+00  1.37441037e+00
  1.53556991e+00  1.83761615e+00  2.04452288e+00  1.11567841e+00
 -9.26529469e-01 -7.29060454e-01 -3.70811621e-03  1.82221113e-01
  6.29510187e-01  1.28312164e-01 -1.05448418e+00  1.90877047e+00
  3.65316448e-01  1.32818573e+00  5.68960954e-02 -4.07526168e-01
 -1.91773046e+00]
Fitness value of the best solution = 897.1374764867876
Predicted output based on the best solution : 0.0011146563667321363

1